# Generated by Django 4.2.6 on 2023-10-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_task_todo_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
