# Generated by Django 4.2.6 on 2023-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_todo_date_todo_iscompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Date',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
