# Generated by Django 4.2.6 on 2023-10-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_todo_date_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_created',
            field=models.DateField(),
        ),
    ]
